export const FETCH_PAGES = "FETCH_PAGES";
export const FETCH_PAGES_SUCCESS = "FETCH_PAGES_SUCCESS";
export const FETCH_PAGES_FAILURE = "FETCH_PAGES_FAILURE";
export const FETCH_PAGE = "FETCH_PAGE";
export const FETCH_PAGE_SUCCESS = "FETCH_PAGE_SUCCESS";
export const FETCH_PAGE_FAILURE = "FETCH_PAGE_FAILURE";
