import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="wrapper">
          <header
            id="header"
            className="w-full z-30 absolute bg-cover bg-center transition-all duration-300"
          >
            <div className="header-wrapper">
              <div className="max-w-[1680px] mx-auto h-86 flex justify-between pt-4 pr-6 pb-4 pl-6">
                <Link href={"/"}>
                  <Image
                    src="/brands/Logo.svg"
                    alt="Logo"
                    width={113}
                    height={54}
                  />
                </Link>
              </div>
            </div>
          </header>
          <main id="main">
            <div id="content">{children}</div>
          </main>
          <footer id="footer"></footer>
        </div>
      </body>
    </html>
  );
}
